### PR TITLE
fix: refactor Actor.selectsRadioButton function

### LINKED ISSUE #558: Refactor "selectsRadioButton" function in Actor.ts
The selectsRadioButton function right now has two issues:

Image

1) The "===" check is too strict, often labels contain more than just an identifying string and can even contain further elements

2) The search for every label in the radioGroup, detemining how many steps are needed to reach that label and then just press the arrow key that many times does work only, if each radio button has just one label element. If there are multiple label elements per radio button (like on the product detail page, when you have subscriptions activated), it doesn't work anymore.

Solutions:
1) Change line 78 to the following should do the trick:
`const desiredOptionIndex = options.findIndex(opt => { return opt.label.includes(inputLabel) });`

2) Maybe instead of finding the label index to determine how many times we need to press the arrow key, we could just press the arrow key in the loop and check every iteration, if the radio button currently focused has the label we want to have. This way it doesn't matter how many additional labels are existing on the lower levels

### PR DESCRIPTION
**Pull request by sguder**
Closes #558 (see for description)

### CODE REVIEW

File: src/services/Actor.ts [hunk 1]
```diff
@@ -56,44 +56,39 @@ export class Actor {
...
+        
+            const maxIterations = await radioGroup.getByRole('radio').count();
+            let iterations = 0;
+        
+            while (!(await desiredOption.isChecked())) {
+                if (iterations >= maxIterations) {
+                    throw new Error(`Could not reach radio button "${inputLabel}" via keyboard navigation.`);
                 }
+        
+                await this.page.keyboard.press('ArrowDown');
```
Comment (ravenokko) [inline src/services/Actor.ts]: `presses()` would be better so that `a11y-checks()` is then run on every radio button as it cycles through.

**Review by yusufttur — APPROVED** [review]

**Review by ravenokko — CHANGES_REQUESTED** [review]

File: src/services/Actor.ts [hunk 2]
```diff
@@ -56,44 +56,39 @@ export class Actor {
...
+                return;
+            }
+        
+            const checkedRadio = radioGroup.getByRole('radio', { checked: true });
+        
+            if (!(await checkedRadio.count())) {
+                throw new Error('No radio button is selected by default.');
+            }
+        
+            await checkedRadio.first().focus();
```
Comment (ravenokko) [inline src/services/Actor.ts]: what does this do, exactly?

Comment (sguder) [reply src/services/Actor.ts]: Sets focus on the element and scrolls it into view if needed, so we have a starting point for keyboard navigation

**Review by ravenokko — APPROVED** [review]

File: src/services/Actor.ts (hunk 1 above)
Comment (sguder) [reply src/services/Actor.ts]: done
